// 来源：公众号@小林coding
// 后端八股网站：xiaolincoding.com
// Agent网站：xiaolinnote.com
// 简历模版：jianli.xiaolinnote.com

const spinnerVerbs = [
  "Accomplishing",
  "Architecting",
  "Baking",
  "Beboppin'",
  "Befuddling",
  "Bloviating",
  "Boogieing",
  "Boondoggling",
  "Bootstrapping",
  "Brewing",
  "Calculating",
  "Canoodling",
  "Caramelizing",
  "Cascading",
  "Cerebrating",
  "Choreographing",
  "Churning",
  "Coalescing",
  "Cogitating",
  "Combobulating",
  "Composing",
  "Computing",
  "Concocting",
  "Considering",
  "Contemplating",
  "Cooking",
  "Crafting",
  "Creating",
  "Crunching",
  "Crystallizing",
  "Cultivating",
  "Deciphering",
  "Deliberating",
  "Dilly-dallying",
  "Discombobulating",
  "Doodling",
  "Elucidating",
  "Enchanting",
  "Envisioning",
  "Fermenting",
  "Finagling",
  "Flambéing",
  "Flibbertigibbeting",
  "Flummoxing",
  "Forging",
  "Frolicking",
  "Gallivanting",
  "Garnishing",
  "Generating",
  "Germinating",
  "Grooving",
  "Harmonizing",
  "Hatching",
  "Honking",
  "Hullaballooing",
  "Ideating",
  "Imagining",
  "Improvising",
  "Incubating",
  "Inferring",
  "Infusing",
  "Kneading",
  "Lollygagging",
  "Manifesting",
  "Marinating",
  "Meandering",
  "Metamorphosing",
  "Mewing",
  "Moonwalking",
  "Moseying",
  "Mulling",
  "Musing",
  "Noodling",
  "Orbiting",
  "Orchestrating",
  "Percolating",
  "Philosophising",
  "Pondering",
  "Pontificating",
  "Pouncing",
  "Purring",
  "Puzzling",
  "Razzle-dazzling",
  "Ruminating",
  "Scampering",
  "Simmering",
  "Sketching",
  "Spelunking",
  "Spinning",
  "Sprouting",
  "Synthesizing",
  "Thinking",
  "Tinkering",
  "Transfiguring",
  "Transmuting",
  "Undulating",
  "Unfurling",
  "Unravelling",
  "Vibing",
  "Wandering",
  "Whisking",
  "Working",
  "Wrangling",
  "Zigzagging",
];

export function randomVerb(): string {
  return spinnerVerbs[Math.floor(Math.random() * spinnerVerbs.length)]!;
}

const completionVerbs = [
  "Accomplished", "Baked", "Brewed", "Cooked", "Crafted",
  "Crunched", "Forged", "Hatched", "Pondered", "Synthesized",
  "Tinkered", "Worked", "Wrangled", "Computed", "Created",
  "Composed", "Conjured", "Concocted", "Cultivated", "Deciphered",
];

export function randomCompletionVerb(): string {
  return completionVerbs[Math.floor(Math.random() * completionVerbs.length)]!;
}
